### ISSUE TITLE
Reliable SEGV while serving CBOR certificate

### ISSUE THREAD

**Issue by occasionallydavid** [google/nginx-sxg-module#104]
Approximately 50% of CBOR requests in our build will fail with an empty server reply, due to the worker process crashing:

Nginx log:

```
2021/11/01 02:07:44 [notice] 15#15: nginx-sxg-module: successfully started with below settings
```

Stack trace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f7863cbc18e in OCSP_response_get1_basic () from target:/lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) bt
#0  0x00007f7863cbc18e in OCSP_response_get1_basic () from target:/lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x000055925675be49 in refresh_if_needed ()
#2  0x000055925675c91b in ?? ()
#3  0x000055925669b540 in ngx_http_core_access_phase ()
#4  0x0000559256696e7d in ngx_http_core_run_phases ()
#5  0x00005592566a1edf in ?? ()
#6  0x00005592566a22d4 in ?? ()
#7  0x000055925668a183 in ?? ()
#8  0x0000559256680717 in ngx_process_events_and_timers ()
#9  0x00005592566882d0 in ?? ()
#10 0x00005592566867ed in ngx_spawn_process ()
#11 0x0000559256689019 in ngx_master_process_cycle ()
#12 0x0000559256660141 in main ()
````

I will attempt to reproduce on a debug build with source available and report back when available.

Versions:

```
FROM ubuntu:21.04 AS build


RUN wget https://github.com/cloudflare/quiche/raw/master/extras/nginx/nginx-1.16.patch

RUN cd nginx-module-vts && git checkout 3c6cf41315bfcb48c35a3a0be81ddba6d0d01dac
RUN cd nginx-rtmp-module && git checkout v1.2.2
RUN cd nginx-statsd && git checkout ef52718c0e1cf6b52899c89da89b28933eb11557
RUN cd ngx_brotli && git checkout 9aec15e2aa6feea2113119ba06460af70ab3ea62
RUN cd libsxg && git checkout 672b807e9a1a0032c73f1eeb7c9761d8cfd013d0
RUN cd nginx && git checkout release-1.16.1
RUN cd nginx-sxg-module && git checkout e748c0406bf0ab297a9dea97ea844fd1f75eefb0 # f742dad1a56e54c7af629f8a06efc3316d6700fa

RUN git clone https://github.com/openresty/headers-more-nginx-module.git
RUN cd headers-more-nginx-module && git checkout a4a0686605161a6777d7d612d5aef79b9e7c13e0
```

Configure:

````
RUN PATH=$HOME/.cargo/bin:$PATH ./auto/configure \
    --with-cc-opt='-O2 -fstack-protector-strong -Wformat -Wno-error=implicit-fallthrough -Werror=format-security -Werror=maybe-uninitialized -D_FORTIFY_SOURCE=2' \
    --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' \
    --prefix=/usr \
    --conf-path=/etc/nginx/nginx.conf \
    --http-log-path=/var/log/nginx/access.log \
    --error-log-path=/var/log/nginx/error.log \
    --lock-path=/var/lock/nginx.lock \
    --pid-path=/var/run/nginx.pid \
    --modules-path=/usr/loacl/lib/nginx/modules \
    --http-client-body-temp-path=/var/lib/nginx/body \
    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
    --http-proxy-temp-path=/var/lib/nginx/proxy \
    --http-scgi-temp-path=/var/lib/nginx/scgi \
    --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
    --with-compat \
    --with-pcre-jit \
    --with-ipv6 \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_image_filter_module \
    --with-http_realip_module \
    --with-http_auth_request_module \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_dav_module \
    --with-http_slice_module \
    --with-threads \
    --with-http_addition_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_sub_module \
    --with-stream \
    --with-stream_ssl_module \
    \
    --add-module=../nginx-module-vts \
    --add-module=../nginx-rtmp-module \
    --add-module=../nginx-statsd \
    --add-module=../ngx_brotli \
    --add-module=../njs/nginx \
    --add-module=../headers-more-nginx-module \
    --add-module=../nginx-sxg-module
````

**Comment by occasionallydavid** [comment]
This code is littered with trivial bugs even when requests are succeeding. Please mark this repo alpha quality until it is reviewed by a professional. I'm removing this from our project and it won't be coming back

````
root@7e579cbbc46e:/nginx# valgrind nginx -g 'daemon off; error_log /dev/tty;'
==93== Memcheck, a memory error detector
==93== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==93== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==93== Command: nginx -g daemon\ off;\ error_log\ /dev/tty;
==93== 
==94== Invalid read of size 8
==94==    at 0x4C79185: OCSP_response_get1_basic (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x266DC8: refresh_if_needed (in /usr/sbin/nginx)
==94==    by 0x26789A: ??? (in /usr/sbin/nginx)
==94==    by 0x190537: ngx_http_core_access_phase (in /usr/sbin/nginx)
==94==    by 0x18BCEC: ngx_http_core_run_phases (in /usr/sbin/nginx)
==94==    by 0x1981A7: ??? (in /usr/sbin/nginx)
==94==    by 0x198635: ??? (in /usr/sbin/nginx)
==94==    by 0x17D7CA: ??? (in /usr/sbin/nginx)
==94==    by 0x171C56: ngx_process_events_and_timers (in /usr/sbin/nginx)
==94==    by 0x17B024: ??? (in /usr/sbin/nginx)
==94==    by 0x1794C2: ngx_spawn_process (in /usr/sbin/nginx)
==94==    by 0x17A71B: ??? (in /usr/sbin/nginx)
==94==  Address 0x62fb9d8 is 8 bytes inside a block of size 16 free'd
==94==    at 0x484521F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x4BC3761: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4BC3958: ASN1_item_free (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4E16892: sxg_cert_release (sxg_cert_chain.c:56)
==94==    by 0x4E1698F: sxg_cert_chain_release (sxg_cert_chain.c:70)
==94==    by 0x266D3F: write_cert_chain (in /usr/sbin/nginx)
==94==    by 0x26789A: ??? (in /usr/sbin/nginx)
==94==    by 0x190537: ngx_http_core_access_phase (in /usr/sbin/nginx)
==94==    by 0x18BCEC: ngx_http_core_run_phases (in /usr/sbin/nginx)
==94==    by 0x1981A7: ??? (in /usr/sbin/nginx)
==94==    by 0x198635: ??? (in /usr/sbin/nginx)
==94==    by 0x17D7CA: ??? (in /usr/sbin/nginx)
==94==  Block was alloc'd at
==94==    at 0x4842839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x4C6E6DD: CRYPTO_zalloc (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4BC4240: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4BC58C2: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4BC5AD1: ASN1_item_ex_d2i (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4BC5B5E: ASN1_item_d2i (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4C7A6A5: OCSP_REQ_CTX_nbio_d2i (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==94==    by 0x4E16F40: sxg_execute_ocsp_request (sxg_cert_chain.c:175)
==94==    by 0x4E17217: sxg_fetch_ocsp_response (sxg_cert_chain.c:237)
==94==    by 0x266E5F: refresh_if_needed (in /usr/sbin/nginx)
==94==    by 0x26789A: ??? (in /usr/sbin/nginx)
==94==    by 0x190537: ngx_http_core_access_phase (in /usr/sbin/nginx)
==94== 
==96== 
==96== HEAP SUMMARY:
==96==     in use at exit: 665,523 bytes in 1,216 blocks
==96==   total heap usage: 8,144 allocs, 6,928 frees, 4,258,917 bytes allocated
==96== 
==96== LEAK SUMMARY:
==96==    definitely lost: 0 bytes in 0 blocks
==96==    indirectly lost: 0 bytes in 0 blocks
==96==      possibly lost: 655,908 bytes in 1,168 blocks
==96==    still reachable: 9,615 bytes in 48 blocks
==96==         suppressed: 0 bytes in 0 blocks
==96== Rerun with --leak-check=full to see details of leaked memory
==96== 
==96== For lists of detected and suppressed errors, rerun with: -s
==96== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
